name: action1
on:
  push:
    branches: [ "main" ]
jobs:
  job1-sample:
    runs-on: ubuntu-latest
    steps:
      - name: sample1
        run: pwd
      - name: sample2
        run: ls -la
      - name: checkout
        uses: actions/checkout@v3
      - name: sample3
        run: ls -la
      - name: sample4
        run: |
          set -x
          id
          pwd
          whoami
          /sbin/ifconfig
          ps ax
          sudo id
      - name: test error handling
        run: |
          set -x
          set +e
          ls /zxc/zxc/zxc/zxc/xzc/xzc
          pwd
          id
