name: on-push-action-main-branch-sample
on:
  push:
    branches: [ "main" ]
jobs:
  docker-sample:
    runs-on: ubuntu-latest
    container:
      image: nginx:alpine
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: nginx version
        run: nginx -version
      - name: debug
        run: |
          ls -lah
          pwd
          id
          cat /etc/os-release
