name: on-push-action-main-branch-sample
on:
  push:
#    branches: [ "main" ]
  paths-ignore:
    - 'docs/***' # Do not invoke the build if changes are only in docs folder.
jobs:
  job1-sample:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' # Example of filtering
    steps:
      - name: sample1
        run: pwd
      - name: sample2
        run: ls -la
      - name: checkout
        uses: actions/checkout@v3
      - name: sample3
        run: ls -la
      - name: sample4
        run: |
          set -x
          id
          pwd
          whoami
          /sbin/ifconfig
          ps ax
          sudo id
      - name: always run
        if: always()
        run: ls -la
      - name: test error handling
        run: |
          set -x
          set +e
          ls /zxc/zxc/zxc/zxc/xzc/xzc
          docker version
          pwd
          id
      - name: use repo secret
        run: |
          echo "mega secret value: '${{ secrets.MEGA_SECRET }}'"
          echo "${{ secrets.MEGA_SECRET }}" > secret-file
          cat secret-file
          wc -c secret-file
