name: strategy-sample
on:
  push:
    branches: [ "main" ]
  paths-ignore:
    - 'docs/***' # Do not invoke the build if changes are only in docs folder.

jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [8, 10]
      max-parallel: 0
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: verify node version
        run: node -v
